apiVersion: v1
kind: Pod
metadata:
  name: Pod-1
  labels:
    app-name: Pod-1
spec:
  containers:
  - name: with-Pod-anti-affinity
    image: registry.k8s.io/pause:3.8
---
apiVersion: v1
kind: Pod
metadata:
  name: Pod-2
  labels:
    app-name: Pod-2
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app-name
            operator: In
            values:
            - Pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: with-Pod-affinity
    image: registry.k8s.io/pause:3.8